# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot_hardware:
      hardware_plugin: "odrive_hardware_interface::ODriveSystemHardware"

    rehab_arm_moveit_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


rehab_arm_moveit_controller:
  ros__parameters:
    joints:
      # - base_joint
      - shoulder_joint
      - elbow_joint
      # - wrist_joint
 
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

